version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: yami
    ports:
      - "3306:3306"
    volumes:
      - ./src/data:/var/lib/mysql
      - ./src/query:/home